### PR TITLE
Port the plugins to Python 3

### PR DESCRIPTION
**Pull request by Freso**
@Silarn is currently working on porting over MO2 to Python 3. I can't really test this conversion (and thus tweak what needs manual tweaking) until his work has produced a test build, but this is a start at least.

### CODE REVIEW

**Comment by deorder** [comment]
Thanks. When the new Python 3 build is ready I will create a separate Python 3 branch and merge in your changes.

**Comment by Freso** [comment]
@Silarn put up a Python 3 build in the MO2 Discord earlier and it seems like the automated `2to3` wasn't enough to make your plugins work smoothly (I didn't really expect it to, but one could hope :) ).

`common.ensureUnicode` seems to cause an issue for `syncModOrder.py`, but just circumventing that (ie., removing the function call) in `PluginWindow.__tr()` isn't enough… now I just get a 'Plugin "<plugin name>" failed:' without an error message (replace <plugin name> with Sync Mod Order/Merge Plugins Hide). Not sure how to debug further without any meaningful error messages/tracebacks.

**Comment by Freso** [comment]
Actually, restarting MO2 seems to have Python-byte-recompiled the plugins and now they work, as long as they don't call `Dc`/`common.ensureUnicode`. Is that function still needed with Py3 having strings as UTF-8 by default?

**Comment by Freso** [comment]
Pushed a commit removing `common.ensureUnicode()`. Sync Mod Order seems to work perfectly for me now, haven't really tried Merge Plugins Hide (or have a setup where it makes sense to test it just now).

**Comment by deorder** [comment]
common.ensureUnicode (an ugly hack) is indeed not needed for Python 3. I created that to convert different kind of types that can encode Unicode characters in them to a byte string.

**Pull request merged**
